// +build !

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/zyseeker/zy-es-operator/pkg/apis/es/v1alpha1.ESCluster":       schema_pkg_apis_es_v1alpha1_ESCluster(ref),
		"github.com/zyseeker/zy-es-operator/pkg/apis/es/v1alpha1.ESClusterSpec":   schema_pkg_apis_es_v1alpha1_ESClusterSpec(ref),
		"github.com/zyseeker/zy-es-operator/pkg/apis/es/v1alpha1.ESClusterStatus": schema_pkg_apis_es_v1alpha1_ESClusterStatus(ref),
	}
}

func schema_pkg_apis_es_v1alpha1_ESCluster(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ESCluster is the Schema for the esclusters API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/zyseeker/zy-es-operator/pkg/apis/es/v1alpha1.ESClusterSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/zyseeker/zy-es-operator/pkg/apis/es/v1alpha1.ESClusterStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/zyseeker/zy-es-operator/pkg/apis/es/v1alpha1.ESClusterSpec", "github.com/zyseeker/zy-es-operator/pkg/apis/es/v1alpha1.ESClusterStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_es_v1alpha1_ESClusterSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ESClusterSpec defines the desired state of ESCluster",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_es_v1alpha1_ESClusterStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ESClusterStatus defines the observed state of ESCluster",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
